/* No accounts, analytics, or remote learning-data storage. */
'use strict';
const $=id=>document.getElementById(id), C=Curriculum, E=QuestEngine, KEY='ailt9004-prototype07-progress-v1';
let storageAvailable=true,progress;
try{progress=E.sanitizeProgress(JSON.parse(localStorage.getItem(KEY)||'null'));}catch{progress=E.freshProgress();storageAvailable=false;}
let selected=C.chapters[0],battle=null,summary=null,voices=[],pickerBook='1-1',toastTimer=null,audioContext=null;
const text=(word)=>word[battle&&!battle.done?battle.settings.script:progress.settings.script];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function save(){try{localStorage.setItem(KEY,JSON.stringify(progress));storageAvailable=true;}catch{storageAvailable=false;}$('storage-warning').hidden=storageAvailable;}
function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,4200);}
const NEURAL_VOICE='neural-xiaoxiao-v1';
const audioFiles=new Map(C.words.flatMap(w=>[[w.traditional,w.id],[w.simplified,w.id]]));
[['聽一聽，是哪一個字詞？','instruction-listen'],['這個字詞是什麼意思？','instruction-meaning'],['找出這個字詞的拼音。','instruction-pinyin'],['這個拼音是哪一個字詞？','instruction-read']].forEach(([label,id])=>audioFiles.set(label,id));
const recordedPlayer=RecordedSpeech.createPlayer({AudioClass:Audio,onLoading:()=>{const b=$('listen-word');if(b&&battle?.question.mode==='listen')b.textContent='◌ 載入語音…';},onPlaying:()=>{const b=$('listen-word');if(b&&battle?.question.mode==='listen')b.textContent='♫ 正在朗讀…';},onEnded:()=>{const b=$('listen-word');if(b&&battle?.question.mode==='listen')b.textContent='▶ 再聽一次';}});
let preloadChapterId=null;
function preloadChapter(){const id=selected.id;preloadChapterId=id;const practice=E.practiceWords(selected,progress),urls=[...practice.map(w=>'assets/audio-neural-v1/'+w.id+'.mp3'),...['listen','meaning','pinyin','read'].map(m=>'assets/audio-neural-v1/instruction-'+m+'.mp3')];recordedPlayer.preload(urls).then(result=>{if(preloadChapterId!==id)return;const label=$('audio-ready');if(label)label.textContent=result.loaded===result.total?'聲音已準備好 · 點字詞聽讀音':'點字詞聽讀音 · 首次播放可能稍等一下';});}
function refreshVoices(){voices=('speechSynthesis'in window)?speechSynthesis.getVoices().filter(v=>/^zh|^cmn/i.test(v.lang)):[];const select=$('voice-setting');const pending=select.value;select.replaceChildren(new Option('自然中文女聲・固定語音',NEURAL_VOICE),new Option('裝置朗讀・自動選擇',''));voices.forEach(v=>select.add(new Option('裝置：'+v.name+' · '+v.lang,v.voiceURI)));select.value=$('settings-dialog').open?pending:progress.settings.voice;$('voice-status').textContent='預設使用預先產生的 AI 中文語音，所有裝置播放同一套聲音。建議使用原速，保留自然節奏。';}
function speak(value,onFailure){const current=battle&&!battle.done?battle.settings:progress.settings;cancelSpeech();const id=audioFiles.get(value);if(current.voice===NEURAL_VOICE&&id){return recordedPlayer.play('assets/audio-neural-v1/'+id+'.mp3',current.rate,()=>{onFailure?.();toast('語音檔未能播放，請再試一次。也可以在家長設定切換成裝置朗讀。');});}
if(!('speechSynthesis'in window)){onFailure?.();toast('這個瀏覽器未支援裝置朗讀，請選自然中文女聲。');return false;}const voice=voices.find(v=>v.voiceURI===current.voice)||voices.find(v=>current.script==='traditional'?/TW/i.test(v.lang):/CN/i.test(v.lang))||voices[0];if(!voice){refreshVoices();onFailure?.();toast('未找到裝置中文聲音。請在家長設定選自然中文女聲。');return false;}const u=new SpeechSynthesisUtterance(value);u.lang=voice.lang;u.voice=voice;u.rate=current.rate;u.onend=()=>{const b=$('listen-word');if(b&&battle?.question.mode==='listen')b.textContent='▶ 再聽一次';};u.onerror=e=>{if(e.error==='canceled'||e.error==='interrupted')return;onFailure?.();toast('這次未能播放，請開啟音量再試。');};speechSynthesis.speak(u);return true;}
function cancelSpeech(){recordedPlayer.stop();if('speechSynthesis'in window)speechSynthesis.cancel();}
function chime(kind){if(!progress.settings.sound)return;try{const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)return;audioContext ||=new Audio();if(audioContext.state==='suspended')audioContext.resume();const notes=kind==='wrong'?[180,140]:kind==='win'?[523,659,784,1046]:[523,784];notes.forEach((freq,i)=>{const o=audioContext.createOscillator(),g=audioContext.createGain(),t=audioContext.currentTime+i*.09;o.type='sine';o.frequency.value=freq;g.gain.setValueAtTime(.045,t);g.gain.exponentialRampToValueAtTime(.001,t+.16);o.connect(g);g.connect(audioContext.destination);o.start(t);o.stop(t+.17);});}catch{/* Audio is optional. */}}
const itemNames={eliminate:'刪選卡',clue:'字詞提示卡',learn:'帶讀通關卡'};
function chapterLabel(c){return `${c.grade} 年級・第 ${c.unit} 單元・第 ${c.lesson} 課`;}
function renderChapters(){
 const [grade,unit]=pickerBook.split('-').map(Number),list=C.chapters.filter(c=>c.grade===grade&&c.unit===unit),won=list.filter(c=>progress.chapters[c.id]?.wins).length;
 $('book-select').value=pickerBook;$('book-count').textContent=`本單元已完成 ${won} / ${list.length} 課`;$('book-bar').style.width=won/list.length*100+'%';
 $('book-description').textContent=`${grade} 年級第 ${unit} 單元 · 完整字詞庫，每場輪練 8 個`;
 $('chapters').innerHTML=list.map(c=>`<button class="chapter-button ${c.id===selected.id?'selected':''}" data-chapter="${c.id}" ${c.id===selected.id?'aria-current="step"':''}><span class="chapter-number">${String(c.lesson).padStart(2,'0')}</span><span><strong>${esc(progress.settings.script==='traditional'?c.title:c.simpleTitle)}</strong><small>${chapterLabel(c)}${c.weeks?` · 第 ${c.weeks} 週`:''}</small>${c.alias?`<small>又名：${esc(c.alias)}</small>`:''}</span><span class="chapter-star" aria-label="${progress.chapters[c.id]?.wins?'已完成':'未完成'}">${progress.chapters[c.id]?.wins?'✦':'·'}</span></button>`).join('');
}
function header(){renderChapters();$('collection-count').textContent=`${Object.keys(progress.words).length} / ${C.words.length}`;const exp=E.experience(progress);$('level').innerHTML=`<strong>Lv. ${exp.level} · 字靈師</strong><small>${exp.current} / ${exp.needed} 經驗</small><span class="xp-mini"><i style="width:${exp.current}%"></i></span>`;$('sound-toggle').textContent=progress.settings.sound?'♫':'♩';$('sound-toggle').setAttribute('aria-label',progress.settings.sound?'關閉遊戲音效':'開啟遊戲音效');$('sound-toggle').setAttribute('aria-pressed',String(progress.settings.sound));
 $('chapter-kicker').textContent=`${chapterLabel(selected)} · ${progress.settings.script==='traditional'?selected.title:selected.simpleTitle}`;$('chapter-title').textContent=selected.story;$('scene-caption').textContent=selected.place+' · THE JADE WOODS';$('storage-warning').hidden=storageAvailable;
}
function choose(id){const chapter=C.chapters.find(c=>c.id===id);if(!chapter)throw Error('找不到章節');if(battle&&!battle.done){if(!window.confirm('離開這場冒險嗎？本場答題進度尚未保存；已獲得的經驗、之前的收藏和星星會保留。'))return false;}cancelSpeech();selected=chapter;pickerBook=`${chapter.grade}-${chapter.unit}`;battle=null;summary=null;home();return true;}
function home(){document.body.classList.remove('in-battle','showing-results','showing-reward');$('scene').classList.remove('victory-scene','level-up');$('dragon').classList.remove('defeat-exit','enemy-arrive');header();$('scene').classList.remove('battle');$('hero').classList.remove('shield');$('dragon').style.opacity='1';$('combat-bars').hidden=true;$('scene-intro').hidden=false;$('map-button').hidden=true;$('mode-badge').hidden=false;const m=progress.settings.mode;$('mode-badge').textContent={listen:'聽一聽・認一認',meaning:'看一看・想一想',pinyin:'認字・選拼音',read:'拼音・找字詞',mixed:'聽音・認字・拼音'}[m];
 const practice=E.practiceWords(selected,progress);
 $('play-area').innerHTML=`<div class="start-card"><div class="start-top"><div><h3>${chapterLabel(selected)} · ${esc(progress.settings.script==='traditional'?selected.title:selected.simpleTitle)}</h3><p>${esc(selected.description)}</p><p class="curriculum-note">${selected.grade} 年級第 ${selected.unit} 單元${selected.alias?` · 又名：${esc(selected.alias)}`:""} · 本課共 ${selected.words.length} 個生字與詞語</p></div><button class="primary" id="start-battle">開始冒險 <span>→</span></button></div><div class="home-growth"><button class="quiet-button" id="home-bag">學習背包 · ${Object.values(progress.inventory).reduce((a,b)=>a+b,0)} 件</button><span>毛筆 Lv. ${E.weapon(E.experience(progress).level).level} · 攻擊 ${E.weapon(E.experience(progress).level).attack} · 最高強化至 Lv. 11</span></div><div class="word-preview">${practice.map(w=>`<button class="word-chip" data-speak="${w.id}">${esc(text(w))}</button>`).join('')}</div><p class="preview-caption"><span id="audio-ready">正在準備這一課的聲音…</span> · 本場 8 個當課字詞${selected.number===1?'':'＋2 個舊詞複習'} · 重玩會輪換本課內容</p><p class="preview-caption">同課經驗：首次 100% · 再玩 60% · 之後 30%；舊詞仍可反覆練習。</p></div>`;
 $('home-bag').addEventListener('click',openBag);$('start-battle').addEventListener('click',start);preloadChapter();}
function start(){document.body.classList.add('in-battle');document.body.classList.remove('showing-results','showing-reward');window.scrollTo(0,0);$('scene').classList.remove('victory-scene','level-up');$('dragon').classList.remove('defeat-exit','enemy-arrive');cancelSpeech();battle=new E.Battle(selected,progress.settings,progress);summary=null;recordedPlayer.preload(battle.reviewTargets.map(w=>'assets/audio-neural-v1/'+w.id+'.mp3'));header();$('scene').classList.add('battle');$('scene-intro').hidden=true;$('combat-bars').hidden=false;$('map-button').hidden=false;$('mode-badge').hidden=true;renderBattle();autoRead();}
function bars(){if(!battle)return;$('hero-hp-label').textContent=battle.heroHp+' / 100';$('hero-hp').style.width=battle.heroHp+'%';$('enemy-hp').style.width=(battle.enemyHp/battle.enemyMaxHp*100)+'%';$('enemy-hp-label').textContent=battle.enemyHp+' / '+battle.enemyMaxHp;$('enemy-name').textContent=battle.defeated?'小龍成為朋友了':(battle.wave===1?'迷霧小龍':'星光小龍')+' Lv. '+battle.monsterLevel;$('wave').textContent=battle.defeated?'再練字詞':`第 ${battle.wave} / 2 波`;$('dragon').style.opacity=battle.defeated?'.45':'1';$('dragon').style.filter=battle.wave===2?'hue-rotate(25deg)':'';}
function optionLabel(w,mode){if(mode==='pinyin')return esc(w.pinyin);if(mode==='meaning')return`${w.emoji?`<span class="emoji" aria-hidden="true">${w.emoji}</span>`:''}<span>${esc(w.meaning)}</span>`;return esc(text(w));}
function renderBattle(){if(battle.phase==='reward'){showReward();return;}if(battle.done){showResult();return;}bars();const q=battle.question,mode=q.mode,resolved=battle.phase==='resolved',correction=battle.phase==='correction',hint=q.revealed||q.basicHint;const typeLabel={listen:'聽音認字',meaning:'理解詞義',pinyin:'認字選拼音',read:'拼音找字詞'}[mode];const title={listen:'聽一聽，是哪一個字詞？',meaning:'這個字詞是什麼意思？',pinyin:'找出這個字詞的拼音。',read:'這個拼音是哪一個字詞？'}[mode];
 const prompt=mode==='listen'?'<button class="listen-big" id="listen-word">▶ 聽一聽</button>':`${esc(mode==='read'?q.word.pinyin:text(q.word))}${mode==='meaning'?'<button class="sound-inline" id="listen-word" aria-label="朗讀字詞">▶</button>':''}`;
 const feedback=correction?`再聽一次：${text(q.word)}（${q.word.pinyin}）。點亮起的答案，再試一次。`:resolved?(battle.lastEvent?.type==='corrected'?'認回來了！小龍也替你開心。':q.assisted?'一起認回來了！稍後再試一次。':'答對了！字靈的力量 +2'):'';
 const hintText=q.word.hasMeaning?q.word.meaning:`拼音：${q.word.pinyin}`;
 $('play-area').innerHTML=`<div class="question-card"><div class="question-top"><span>第 ${battle.turn} 題 · ${q.review?"舊詞複習":"當課字詞"} · ${typeLabel}</span><button id="read-instruction" aria-label="朗讀題目指示">▶ 聽題目</button></div><h3 class="question-title" id="question-heading" tabindex="-1">${title}</h3><div class="prompt ${mode==='read'?'pinyin-prompt':''}">${prompt}</div>${hint?`<div class="hint-box">${q.revealed?`${esc(text(q.word))} · `:"提示："}${esc(hintText)}</div>`:''}<div class="answers" style="--choice-count:${q.options.length}">${q.options.map((w,i)=>`<button class="answer ${mode==='meaning'?'meaning-answer':mode==='pinyin'?'pinyin-answer':''} ${(resolved||correction)&&w.id===q.word.id?'correct':''} ${correction&&w.id===q.wrongId?'wrong':''} ${q.eliminated.includes(w.id)?'eliminated':''}" data-answer="${w.id}" ${resolved||q.eliminated.includes(w.id)?'disabled':''}><span class="answer-key" aria-hidden="true">${i+1}</span>${optionLabel(w,mode)}</button>`).join('')}</div><div class="feedback ${correction?'error':''}" role="status">${esc(feedback)}</div>${resolved?'<div class="continue-row"><button class="primary" id="next-question">繼續冒險 →</button></div>':`<div class="question-top question-help"><button id="free-hint" ${q.basicHint||q.revealed?'disabled':''}>✧ ${q.word.hasMeaning?'意思':'拼音'}提示（免費）</button>${mode==='listen'?'<button id="visual-fallback">聽不到？改用看字</button>':''}</div>`}<div class="energy-heading"><span>✦ 字靈能量 <b>${battle.energy} / 6</b></span><span class="energy-track" aria-hidden="true">${Array.from({length:6},(_,i)=>`<i class="${i<battle.energy?'filled':''}"></i>`).join('')}</span></div><div class="skills"><button class="skill" data-skill="fire" ${battle.energy<3||battle.phase!=='answer'||battle.defeated||battle.enemyHp===0?'disabled':''}><span class="symbol">✹</span><span><strong>毛筆攻擊</strong><small>3 能量 · 攻擊 ${battle.weapon.skill}</small></span></button><button class="skill" data-skill="heal" ${battle.energy<3||battle.phase!=='answer'||battle.heroHp===100?'disabled':''}><span class="symbol">♡</span><span><strong>補血法術</strong><small>3 能量 · 回血 35</small></span></button><button class="skill bag-button" id="battle-bag"><span class="symbol">▣</span><span><strong>學習背包</strong><small>${Object.values(progress.inventory).reduce((a,b)=>a+b,0)} 件 · 卡關時使用</small></span></button></div></div>`;
 $('battle-bag').addEventListener('click',openBag);$('listen-word')?.addEventListener('click',()=>{if(mode==='listen'||mode==='meaning')speakWord();});$('read-instruction').addEventListener('click',()=>speak(title));$('free-hint')?.addEventListener('click',()=>{battle.freeHint();renderBattle();});$('visual-fallback')?.addEventListener('click',()=>{cancelSpeech();q.mode=q.word.hasMeaning?'meaning':'pinyin';renderBattle();toast(q.word.hasMeaning?'已改用看字選意思，這一題不需要聲音。':'已改用看字選拼音，這一題不需要聲音。');});$('next-question')?.addEventListener('click',next);
}
function speakWord(){if(!battle)return;const playing=speak(text(battle.word),()=>{const b=$('listen-word');if(b)b.textContent='▶ 再試一次';});if(playing&&$('listen-word')&&battle.question.mode==='listen'&&battle.settings.voice!==NEURAL_VOICE)$('listen-word').textContent='♫ 正在朗讀…';}
function autoRead(){if(battle?.question.mode==='listen')speakWord();}
function effect(message,target,kind){$('battle-effect').textContent=message;$('battle-effect').classList.remove('pop');void $('battle-effect').offsetWidth;$('battle-effect').classList.add('pop');const el=$(target);el.classList.remove('attack','hit');void el.offsetWidth;el.classList.add(kind);setTimeout(()=>el.classList.remove(kind),600);}
function answer(id){if(!battle||battle.done)return;const event=battle.answer(id);if(event.type==='ignored')return;if(event.type==='try-again'){toast('選亮起的字詞，我們一起認一次。');return;}cancelSpeech();if(battle.phase==='reward'){showReward();return;}renderBattle();if(event.type==='wrong'){chime('wrong');effect(event.rescue?'伙伴救援 +55':'生命 −15','hero','hit');speak(text(battle.word));if(event.rescue)toast('字靈伙伴幫你回血了！慢慢來，我們繼續。');}else{chime('correct');effect('✦ −'+event.damage,'dragon','hit');$('hero').classList.add('attack');setTimeout(()=>$('hero').classList.remove('attack'),500);$('next-question')?.focus({preventScroll:true});}}
function skill(name){if(!battle)return;const event=battle.useSkill(name);if(['ignored','unavailable','full-health'].includes(event.type))return;if(battle.phase==='reward'){showReward();return;}renderBattle();if(event.type==='heal'){effect('♡ +35','hero','attack');chime('correct');}else if(event.type==='hint'){toast('字靈幫你排除了一個選項。');speak(text(battle.word));}else{effect('✹ 毛筆攻擊 −'+battle.weapon.skill,'dragon','hit');chime('correct');if(event.type==='fire-wave')toast('第一隻小龍交到了朋友！第二隻登場。');if(event.type==='fire-defeated')toast('小龍被你打敗了！完成眼前這一題，把字詞帶回家。');}}
function showReward(){document.body.classList.add('showing-reward');cancelSpeech();save();header();bars();const r=battle.reward,up=r.after.level>r.before.level;$('scene').classList.add('victory-scene');$('scene').classList.toggle('level-up',up);$('dragon').classList.add('defeat-exit');$('wave').textContent='勝利！';effect('✦ 擊敗小龍！','hero','attack');chime('win');
 $('play-area').innerHTML=`<div class="reward-card" role="status"><span class="reward-kicker">MONSTER DEFEATED</span><h3>${r.wave===1?'迷霧小龍':'星光小龍'}被你打敗了！</h3><div class="xp-gain">+${r.amount}<span>經驗值</span></div>${up?`<div class="level-up-message">✦ 升級了！ Lv. ${r.before.level} → Lv. ${r.after.level}<small>毛筆攻擊 ${E.weapon(r.before.level).attack} → ${E.weapon(r.after.level).attack} · ${r.healed?'回血 +'+r.healed:'生命充滿'}</small></div>`:`<p>毛筆攻擊 ${battle.weapon.attack} · 下一級 ${E.weapon(r.after.level+1).attack}</p>`}<div class="reward-progress"><span>Lv. ${r.after.level}</span><div class="track"><i style="width:${r.after.current}%"></i></div><span>${r.after.current} / 100</span></div><p class="session-note">本課獎勵 ${Math.round(battle.rewardRate*100)}% · 經驗已記錄${r.wave===1?' · 準備好再繼續下一場！':''}</p><button class="primary" id="claim-reward">${r.wave===1?'迎接下一隻 →':r.resume==='question'?'完成這一題 →':'收下獎勵，完成字詞 →'}</button></div>`;
 $('claim-reward').addEventListener('click',()=>{if(battle.phase!=='reward')return;document.body.classList.remove('showing-reward');$('scene').classList.remove('victory-scene','level-up');$('dragon').classList.remove('defeat-exit');const oldWave=battle.wave;battle.continueReward();if(battle.done){showResult();return;}renderBattle();if(battle.wave!==oldWave){$('dragon').classList.add('enemy-arrive');setTimeout(()=>$('dragon').classList.remove('enemy-arrive'),800);}autoRead();});$('claim-reward').focus({preventScroll:true});}
function next(){if(!battle)return;cancelSpeech();const previous=battle.wave;battle.advance();if(battle.done){showResult();return;}renderBattle();if(battle.wave!==previous)toast('第二波！星光小龍來了。');$('question-heading')?.focus({preventScroll:true});autoRead();}
function showResult(){document.body.classList.add('showing-results');document.body.classList.remove('showing-reward');if(!summary){summary=battle.finish();save();chime('win');}header();bars();$('map-button').hidden=true;$('scene-intro').hidden=true;$('wave').textContent='冒險完成';const s=summary,next=C.chapters[selected.number%C.chapters.length],cross=next.grade!==selected.grade||next.unit!==selected.unit;$('play-area').innerHTML=`<div class="result-card"><div class="result-stars" aria-label="${s.stars} 顆星">${'★'.repeat(s.stars)}${'☆'.repeat(3-s.stars)}</div><h3>你找回了發光的字！</h3><p>小龍加入了你的冒險。今天的每一次嘗試，都算數。</p><div class="result-xp">✦ 本場 +${s.xp} 經驗 · Lv. ${s.level}</div><div class="result-stats"><div><strong>${s.words.length}</strong><span>個字詞練習</span></div><div><strong>${s.correct}</strong><span>次答對</span></div><div><strong>${s.mistakes}</strong><span>次一起訂正</span></div></div><p class="item-earned">${s.item?`獲得 ${itemNames[s.item]} ×1，已放入學習背包`:"這次獲得的道具已存滿 9 張，先用一張幫自己學字！"}</p><div class="result-actions"><button class="secondary" id="replay">再玩這一章</button><button class="primary" id="next-chapter">${selected.number<C.chapters.length?(cross?'前往下一單元 →':'下一課 →'):'回到第一課 →'}</button></div>${s.review.length?'<p>這幾個字，下次我們再見一次：</p>':'<p>今天的字詞，都被你點亮了。</p>'}<div class="result-words">${(s.review.length?s.review:s.words).map(id=>C.words.find(w=>w.id===id)).filter(Boolean).map(w=>`<button class="word-chip" data-speak="${w.id}">${esc(text(w))}<small>${esc(w.pinyin)}</small></button>`).join('')}</div><p class="session-note">${storageAvailable?'星星與字詞已保存到這個瀏覽器。':'這個瀏覽器無法保存，請先保留此頁。'}</p></div>`;$('replay').addEventListener('click',start);$('next-chapter').addEventListener('click',()=>choose(next.id));}

function openBag(){
 const active=battle&&!battle.done&&['answer','correction'].includes(battle.phase),q=active?battle.question:null;
 const descriptions={eliminate:'4 選項刪掉 2 個；3 選項刪掉 1 個。保留至少兩個答案。',clue:'看這個字詞與拼音；有詞義提示時也一起看，再聽完整讀音。',learn:'先看字詞並跟著念，再按「學過了，繼續」通過這題；稍後再練。'};
 $('bag-content').innerHTML=`<p>道具幫你學字，不算獨立答對。用過的字會再練一次。每種最多存 9 張。</p>${E.ITEMS.map(kind=>{const unavailable=!active||!progress.inventory[kind]||q.usedItems.includes(kind)||(kind==='eliminate'&&(q.options.length<3||battle.phase!=='answer'||q.eliminated.length));return `<div class="bag-item"><div><h3>${itemNames[kind]} <span>× ${progress.inventory[kind]}</span></h3><p>${descriptions[kind]}</p>${kind==='eliminate'&&q?.options.length===2?'<small>這題只有兩個選項，請選其他道具。</small>':''}</div><button class="secondary" data-item="${kind}" ${unavailable?'disabled':''}>使用</button></div>`;}).join('')}<p>${active?'沒有道具也能使用題目下方的免費意思提示。':'開始答題後就可以使用。新背包每種送兩張；完成一整課再送一張。'}</p>`;
 $('bag-dialog').showModal();
}
$('bag-content').addEventListener('click',e=>{
 const b=e.target.closest('[data-item]');if(!b||b.disabled||!battle)return;
 const result=battle.useItem(b.dataset.item);if(result.type==='unavailable')return;save();renderBattle();
 if(result.type==='eliminate'){$('bag-dialog').close();toast('已排除錯誤選項，現在自己選一選。');return;}
 const word=battle.word;
 $('bag-content').innerHTML=`<div class="study-card"><p>${result.type==='learn'?'先學再通過':'看一看，念一念'}</p><h3>${esc(text(word))}</h3><p>${esc(word.pinyin)}${word.hasMeaning?' · '+esc(word.meaning):''}</p><button class="secondary" data-speak="${word.id}">▶ 再聽一次</button><p>跟著念一次；這個字稍後還會回來。</p><button class="primary" id="study-done">${result.type==='learn'?'學過了，繼續':'回題目自己選'}</button></div>`;
 speak(text(word));$('study-done').addEventListener('click',()=>{$('bag-dialog').close();if(result.type==='learn'&&battle.word.id===word.id)answer(word.id);});
});

function collection(){const learned=C.words.filter(w=>progress.words[w.id]);const familiar=learned.filter(w=>E.mastered(progress.words[w.id])).length;$('collection-summary').textContent=`已遇見 ${learned.length} / ${C.words.length} 個字詞 · 熟悉 ${familiar} 個`;$('collection-grid').innerHTML=learned.length?learned.map(w=>`<button class="collection-item ${E.mastered(progress.words[w.id])?'mastered':''}" data-speak="${w.id}"><strong>${esc(text(w))}</strong><small>${esc(w.pinyin)}<br>${E.mastered(progress.words[w.id])?'✦ 熟悉':'✧ 再認一次'}</small></button>`).join(''):'<p>完成第一場冒險，就能在這裡找到你的字詞。</p>';$('collection-dialog').showModal();}
function openSettings(){refreshVoices();const s=progress.settings;$('script-setting').value=s.script;$('mode-setting').value=s.mode;$('options-setting').value=String(s.options);$('rate-setting').value=String(s.rate);$('voice-setting').value=s.voice;$('settings-dialog').showModal();}
$('book-select').addEventListener('change',()=>{pickerBook=$('book-select').value;renderChapters();});
$('chapters').addEventListener('click',e=>{const b=e.target.closest('[data-chapter]');if(b&&choose(b.dataset.chapter)){$('chapter-dialog').close();$('chapter-open').focus({preventScroll:true});}});
$('play-area').addEventListener('click',e=>{const a=e.target.closest('[data-answer]'),s=e.target.closest('[data-skill]');if(a&&!a.disabled)answer(a.dataset.answer);if(s&&!s.disabled)skill(s.dataset.skill);});
document.addEventListener('click',e=>{const b=e.target.closest('[data-speak]');if(b){const w=C.words.find(w=>w.id===b.dataset.speak);if(w)speak(text(w));}});
$('map-button').addEventListener('click',()=>choose(selected.id));document.querySelector('.brand').addEventListener('click',e=>{e.preventDefault();choose(selected.id);});$('chapter-open').addEventListener('click',()=>{pickerBook=`${selected.grade}-${selected.unit}`;renderChapters();$('chapter-dialog').showModal();$('chapters').querySelector('[aria-current]')?.focus();});$('review-open').addEventListener('click',()=>{$('chapter-dialog').close();collection();});$('parent-open').addEventListener('click',openSettings);$('about-open').addEventListener('click',()=>$('about-dialog').showModal());$('sound-toggle').addEventListener('click',()=>{progress.settings.sound=!progress.settings.sound;save();header();toast(progress.settings.sound?'遊戲音效已開啟。':'遊戲音效已關閉；字詞朗讀仍然可用。');});
$('test-voice').addEventListener('click',()=>{const old=battle;battle=null;const previous={...progress.settings};progress.settings.voice=$('voice-setting').value;progress.settings.rate=Number($('rate-setting').value);progress.settings.script=$('script-setting').value;speak('眼睛');progress.settings=previous;battle=old;});
$('save-settings').addEventListener('click',()=>{Object.assign(progress.settings,{script:$('script-setting').value,mode:$('mode-setting').value,options:Number($('options-setting').value),rate:Number($('rate-setting').value),voice:$('voice-setting').value});save();$('settings-dialog').close();if(!battle||battle.done){battle=null;home();}toast('設定已保存，下一場冒險開始使用。');});
document.addEventListener('keydown',e=>{if(document.querySelector('dialog[open]')||e.repeat||!battle||battle.done||/INPUT|SELECT|TEXTAREA/.test(e.target.tagName))return;if(['1','2','3','4'].includes(e.key)){const w=battle.question.options[Number(e.key)-1];if(w){e.preventDefault();answer(w.id);}}});
if('speechSynthesis'in window)speechSynthesis.addEventListener('voiceschanged',refreshVoices);refreshVoices();window.addEventListener('pagehide',cancelSpeech);
home();
