const test=require('node:test');const assert=require('node:assert/strict');
const E=require('../engine.js'),C=require('../curriculum.js');
function battle(chapter=0,settings={},progress=E.freshProgress()){return new E.Battle(C.chapters[chapter],{...progress.settings,mode:'listen',...settings},progress,()=>.42);}
function finish(b,options={}){let safety=0;while(!b.done&&safety++<100){if(options.fire&&b.energy>=3)b.useSkill('fire');if(options.wrong){const bad=b.question.options.find(w=>w.id!==b.word.id);b.answer(bad.id);}b.answer(b.word.id);if(b.phase==='reward')b.continueReward();else b.advance();}assert.ok(b.done,'battle must terminate');return b.finish();}
test('two books, fourteen lessons, 112 unique valid practice items',()=>{assert.equal(C.chapters.length,14);assert.equal(C.words.length,112);assert.equal(new Set(C.words.map(w=>w.id)).size,112);for(const c of C.chapters){assert.equal(c.words.length,8);for(const w of c.words)for(const f of ['traditional','simplified','meaning','pinyin'])assert.ok(w[f]);}});
test('every chapter / mode / script / option count completes without skill',()=>{for(let i=0;i<C.chapters.length;i++)for(const mode of [...E.MODES,'mixed'])for(const script of ['traditional','simplified'])for(const options of [2,3,4]){const b=battle(i,{mode,script,options});while(!b.done){const q=b.question;assert.equal(q.options.length,options);const field=q.mode==='pinyin'?'pinyin':q.mode==='meaning'?'meaning':script;assert.equal(new Set(q.options.map(w=>w[field])).size,options);b.answer(b.word.id);if(b.phase==='reward')b.continueReward();else b.advance();}assert.equal(b.turn,i===0?8:10);assert.equal(b.heroHp,100);assert.equal(b.finish().stars,3);}});
test('wrong choice hurts once, locks into correction, revisits word',()=>{const b=battle();const id=b.word.id;const wrong=b.question.options.find(w=>w.id!==id);assert.equal(b.answer(wrong.id).type,'wrong');assert.equal(b.heroHp,85);assert.equal(b.phase,'correction');assert.equal(b.answer(wrong.id).type,'try-again');assert.equal(b.heroHp,85);b.answer(id);assert.equal(b.phase,'resolved');assert.equal(b.energy,1);assert.equal(b.enemyHp,85);assert.ok(b.queue.some(w=>w.id===id));const hp=b.enemyHp;b.answer(id);assert.equal(b.enemyHp,hp);});
test('repeated mistakes rescue child and still reach completion',()=>{const b=battle();const s=finish(b,{wrong:true});assert.ok(s.rescues>=1);assert.equal(s.stars,1);assert.ok(b.heroHp>0);assert.ok(s.review.length);});
test('energy cannot be spent before earned; healing clamps',()=>{const b=battle();assert.equal(b.useSkill('fire').type,'unavailable');b.energy=3;assert.equal(b.useSkill('heal').type,'full-health');assert.equal(b.energy,3);b.heroHp=90;assert.equal(b.useSkill('heal').type,'heal');assert.equal(b.heroHp,100);assert.equal(b.energy,0);});
test('fire shortens combat; queued missed words still reappear',()=>{const normal=battle();finish(normal);const fast=battle();finish(fast,{fire:true});assert.equal(fast.turn,normal.turn);assert.equal(new Set(fast.results.map(r=>r.wordId)).size,8);const b=battle();const missed=b.word.id;b.answer(b.question.options.find(w=>w.id!==missed).id);b.answer(missed);if(b.phase==='reward')b.continueReward();else b.advance();finish(b,{fire:true});assert.ok(b.results.filter(r=>r.wordId===missed).length>=2);});
test('hint removes only a distractor and never grants independent mastery',()=>{const p=E.freshProgress(),b=battle(0,{},p);const id=b.word.id;b.energy=6;assert.equal(b.useSkill('hint').type,'hint');assert.equal(b.energy,4);assert.equal(b.question.eliminated.length,1);assert.notEqual(b.question.eliminated[0],id);assert.equal(b.useSkill('hint').type,'unavailable');assert.equal(b.answer(b.question.eliminated[0]).type,'ignored');b.answer(id);if(b.phase==='reward')b.continueReward();else b.advance();finish(b);assert.equal(b.results.find(r=>r.wordId===id).independent,false);assert.equal(E.mastered(p.words[id]),false);});
test('free hints work with zero energy and mark the result assisted',()=>{const b=battle();assert.equal(b.freeHint(),true);assert.equal(b.freeHint(),false);b.answer(b.word.id);assert.equal(b.results[0].independent,false);assert.equal(b.energy,2);});
test('winning persists once; familiarity needs two separate sessions',()=>{const p=E.freshProgress();const b=battle(0,{},p);finish(b);assert.equal(p.sessions,1);assert.equal(b.finish(),null);assert.equal(p.sessions,1);assert.ok(Object.values(p.words).every(w=>!E.mastered(w)));const b2=battle(0,{},p);finish(b2);assert.ok(Object.values(p.words).every(E.mastered));assert.equal(p.chapters.eyes.wins,2);});
test('a new question cannot be skipped; invalid answer has no effect',()=>{const b=battle();assert.equal(b.advance(),false);assert.equal(b.answer('bad-id').type,'ignored');assert.equal(b.turn,1);assert.equal(b.heroHp,100);});
test('progress round trip preserves settings and accomplishments',()=>{const p=E.freshProgress();finish(battle(2,{},p));p.settings.mode='read';p.settings.script='simplified';assert.deepEqual(E.sanitizeProgress(JSON.parse(JSON.stringify(p))),p);const corrupted=E.sanitizeProgress({settings:{mode:'nonsense',options:100,rate:-1},sessions:-2});assert.equal(corrupted.settings.mode,'mixed');assert.equal(corrupted.settings.options,2);assert.equal(corrupted.sessions,0);});
test('assisted sessions cannot dilute best star record',()=>{const p=E.freshProgress();finish(battle(0,{},p));finish(battle(0,{},p),{wrong:true});assert.equal(p.chapters.eyes.stars,3);});
test('sound and written choices never reveal answers through mismatched lengths',()=>{for(let i=0;i<C.chapters.length;i++)for(const mode of ['listen','read','pinyin']){const b=battle(i,{mode,options:4});while(!b.done){for(const option of b.question.options)assert.ok(E.sameLength(option,b.word),`${mode}: ${b.word.traditional}/${option.traditional}`);assert.equal(b.question.options.length,4);if(mode!=='pinyin')assert.equal(new Set(b.question.options.map(w=>w.pinyin)).size,4);b.answer(b.word.id);if(b.phase==='reward')b.continueReward();else b.advance();}}});
test('mixed mode rotates three complementary question formats',()=>{const b=battle(0,{mode:'mixed'}),modes=[];while(!b.done){modes.push(b.question.mode);b.answer(b.word.id);if(b.phase==='reward')b.continueReward();else b.advance();}assert.deepEqual(modes.slice(0,6),['listen','pinyin','read','listen','pinyin','read']);});
test('pinyin options include distinct same-length tone contrasts',()=>{const b=battle(0,{mode:'pinyin',options:4});assert.equal(new Set(b.question.options.map(w=>w.pinyin)).size,4);assert.ok(b.question.options.some(w=>w.id.includes('-tone-')));assert.ok(b.question.options.every(w=>E.sameLength(w,b.word)));});
test('legacy listen default becomes mixed once; explicit new preferences persist',()=>{const old=E.sanitizeProgress({settings:{mode:'listen'},sessions:3,chapters:{eyes:{stars:2,wins:1}}});assert.equal(old.settings.mode,'mixed');assert.equal(old.sessions,3);assert.equal(old.chapters.eyes.stars,2);old.settings.mode='listen';assert.equal(E.sanitizeProgress(old).settings.mode,'listen');});
test('defeating a monster pauses for rewards and awards XP exactly once',()=>{const p=E.freshProgress(),b=battle(0,{},p);for(let i=0;i<4;i++){b.answer(b.word.id);if(i<3)b.advance();}assert.equal(b.phase,'reward');assert.equal(b.wave,1);assert.equal(b.enemyHp,0);assert.equal(p.xp,40);assert.equal(b.advance(),false);assert.equal(b.answer(b.word.id).type,'ignored');assert.equal(b.beginReward('advance'),false);assert.equal(p.xp,40);assert.equal(b.continueReward(),true);assert.equal(b.wave,2);assert.equal(b.enemyHp,100);assert.equal(b.continueReward(),false);assert.equal(p.xp,40);});
test('skill kill pauses then resumes the unanswered question',()=>{const b=battle();b.enemyHp=30;b.energy=3;const id=b.word.id,turn=b.turn;b.useSkill('fire');assert.equal(b.phase,'reward');assert.equal(b.progress.xp,40);b.continueReward();assert.equal(b.word.id,id);assert.equal(b.turn,turn);assert.equal(b.phase,'answer');assert.equal(b.wave,2);assert.equal(b.enemyHp,100);});
test('second monster levels the hero up and applies a bounded heal',()=>{const p=E.freshProgress(),b=battle(0,{},p);let safety=0;while(b.phase!=='reward'&&safety++<10){b.answer(b.word.id);if(b.phase!=='reward')b.advance();}b.continueReward();b.heroHp=65;safety=0;while(b.phase!=='reward'&&safety++<10){b.answer(b.word.id);if(b.phase!=='reward')b.advance();}assert.equal(p.xp,100);assert.equal(b.reward.after.level,2);assert.equal(b.reward.healed,25);assert.equal(b.heroHp,90);const restored=E.sanitizeProgress(JSON.parse(JSON.stringify(p)));assert.equal(E.experience(restored).level,2);b.continueReward();assert.ok(b.done);assert.equal(b.finish().xp,100);assert.equal(p.xp,100);});
test('legacy progress starts at level one and invalid XP is discarded',()=>{assert.equal(E.experience(E.sanitizeProgress({sessions:2})).level,1);assert.equal(E.sanitizeProgress({xp:-10}).xp,0);assert.equal(E.sanitizeProgress({xp:'100'}).xp,0);assert.equal(E.experience({xp:240}).level,3);assert.equal(E.experience({xp:240}).current,40);});
test('book and lesson mapping follows teaching weeks; review pools never include later lessons',()=>{
 for(const book of [1,2]){const lessons=C.chapters.filter(c=>c.book===book);assert.deepEqual(lessons.map(c=>c.lesson),[1,2,3,4,5,6,7]);assert.deepEqual(lessons.map(c=>c.weeks),book===1?['1','2','3–4','5','6','7','8']:['1','2','3','4','5–6','7','8']);}
 for(const c of C.chapters)for(const w of c.reviewWords)assert.ok(C.chapters.find(ch=>ch.words.some(item=>item.id===w.id)).number<=c.number);
 assert.match(C.chapters.find(c=>c.id==='moon').alias,/彎彎的月亮/);
});
test('Book 2 practice words use characters introduced by their mapped lesson',()=>{
 // Public Grade 1 character list: current lesson plus previously introduced characters.
 const scope=['雨千万条线掉进水风云雪','镜他也哭笑脸脏就知道爸妈爱','袋鼠奇怪好胸挂放果菜娃爬来米田石木土','画远色近听无声春人','蝌蚪细身脑长着变啦了腿脱衣服换裤褂咦成青蛙','弯的月亮船尖闪星天日火','牛匹马件羊群鸭桃百鱼虫草'];
 const known=new Set(C.chapters.filter(c=>c.book===1).flatMap(c=>c.words.flatMap(w=>Array.from(w.simplified))));
 for(const c of C.chapters.filter(c=>c.book===2)){for(const ch of scope[c.lesson-1])known.add(ch);for(const w of c.words)for(const ch of w.simplified)assert.ok(known.has(ch),`${c.id}: ${ch}`);}
});
test('review targets are 20 percent, prioritize known difficult words, and never come from later lessons',()=>{
 const p=E.freshProgress(),c=C.chapters[7];p.words['eyes-0']={seen:2,mistakes:2,modes:{}};p.words['ears-1']={seen:1,mistakes:1,modes:{}};
 const b=battle(7,{},p);assert.equal(b.plannedCount,10);assert.deepEqual(new Set(b.reviewTargets.map(w=>w.id)),new Set(['eyes-0','ears-1']));
 assert.equal(battle().plannedCount,8);assert.equal(battle().reviewTargets.length,0);
});
test('all lesson targets and scheduled reviews survive maximum weapon damage and repeated fire',()=>{
 for(let i=0;i<C.chapters.length;i++){const p=E.freshProgress();p.xp=10000;const b=battle(i,{options:4},p);finish(b,{fire:true});const seen=new Set(b.results.map(r=>r.wordId));for(const w of [...C.chapters[i].words,...b.reviewTargets])assert.ok(seen.has(w.id),w.id);}
});
test('inventory migrates, clamps invalid values, spends once and persists consumption',()=>{
 const old=E.sanitizeProgress({xp:300});assert.deepEqual(old.inventory,{eliminate:2,clue:2,learn:2});
 assert.deepEqual(E.sanitizeProgress({inventory:{eliminate:-1,clue:1000,learn:'9'}}).inventory,{eliminate:0,clue:9,learn:0});
 const b=battle(0,{options:4});assert.equal(b.useItem('eliminate').type,'eliminate');assert.equal(b.question.eliminated.length,2);assert.ok(!b.question.eliminated.includes(b.word.id));assert.equal(b.progress.inventory.eliminate,1);assert.equal(b.useItem('eliminate').type,'unavailable');assert.equal(E.sanitizeProgress(b.progress).inventory.eliminate,1);
 const two=battle();assert.equal(two.useItem('eliminate').type,'unavailable');assert.equal(two.progress.inventory.eliminate,2);
});
test('learning items and free clues revisit without granting independent success for the assisted answer',()=>{
 for(const kind of ['clue','learn']){const b=battle();const id=b.word.id;b.useItem(kind);assert.equal(b.question.revealed,true);assert.ok(b.queue.some(w=>w.id===id));b.answer(id);assert.equal(b.results[0].independent,false);if(b.phase==='reward')b.continueReward();else b.advance();finish(b);assert.ok(b.results.filter(r=>r.wordId===id).length>=2);}
 const b=battle();b.freeHint();assert.equal(b.question.basicHint,true);assert.equal(b.question.revealed,false);
});
test('same lesson XP diminishes and partial reward claims cannot reset it',()=>{
 const p=E.freshProgress();const amounts=[];for(let i=0;i<3;i++)amounts.push(finish(battle(0,{},p)).xp);assert.deepEqual(amounts,[100,60,30]);
 const partial=E.freshProgress();for(let i=0;i<2;i++){const b=battle(0,{},partial);b.enemyHp=1;b.answer(b.word.id);assert.equal(b.phase,'reward');}
 assert.equal(battle(0,{},E.sanitizeProgress(partial)).rewardRate,.6);
});
test('weapon grows gradually and monsters keep an easier wave without reacting mid-battle',()=>{
 assert.equal(E.weapon(1).attack,25);assert.equal(E.weapon(2).attack,27);assert.equal(E.weapon(100).attack,45);
 const p=E.freshProgress();p.xp=400;const b=battle(7,{},p),first=b.monsterLevel;assert.equal(first,2);b.enemyHp=1;b.answer(b.word.id);b.continueReward();assert.equal(b.monsterLevel,first+1);assert.equal(b.enemyHp,b.enemyMaxHp);assert.ok(b.enemyMaxHp<=150);
});
test('whole-lesson supply is awarded exactly once and respects inventory cap',()=>{
 const b=battle();const s=finish(b);assert.equal(s.item,'eliminate');assert.equal(b.progress.inventory.eliminate,3);assert.equal(b.finish(),null);assert.equal(b.progress.inventory.eliminate,3);
 const p=E.freshProgress();p.inventory.eliminate=9;assert.equal(finish(battle(0,{},p)).item,null);assert.equal(p.inventory.eliminate,9);
});
