const test=require('node:test');const assert=require('node:assert/strict');
const E=require('../engine.js'),C=require('../curriculum.js');
function battle(chapter=0,settings={},progress=E.freshProgress()){return new E.Battle(C.chapters[chapter],{...progress.settings,mode:'listen',...settings},progress,()=>.42);}
function finish(b,options={}){let safety=0;while(!b.done&&safety++<100){if(options.fire&&b.energy>=3)b.useSkill('fire');if(options.wrong){const bad=b.question.options.find(w=>w.id!==b.word.id);b.answer(bad.id);}b.answer(b.word.id);if(b.phase==='reward')b.continueReward();else b.advance();}assert.ok(b.done,'battle must terminate');return b.finish();}
test('seven chapters, 56 unique valid practice items',()=>{assert.equal(C.chapters.length,7);assert.equal(C.words.length,56);assert.equal(new Set(C.words.map(w=>w.id)).size,56);for(const c of C.chapters){assert.equal(c.words.length,8);for(const w of c.words)for(const f of ['traditional','simplified','meaning','pinyin'])assert.ok(w[f]);}});
test('every chapter / mode / script / option count completes without skill',()=>{for(let i=0;i<7;i++)for(const mode of [...E.MODES,'mixed'])for(const script of ['traditional','simplified'])for(const options of [2,3,4]){const b=battle(i,{mode,script,options});while(!b.done){const q=b.question;assert.equal(q.options.length,options);const field=q.mode==='pinyin'?'pinyin':q.mode==='meaning'?'meaning':script;assert.equal(new Set(q.options.map(w=>w[field])).size,options);b.answer(b.word.id);if(b.phase==='reward')b.continueReward();else b.advance();}assert.equal(b.turn,8);assert.equal(b.heroHp,100);assert.equal(b.finish().stars,3);}});
test('wrong choice hurts once, locks into correction, revisits word',()=>{const b=battle();const id=b.word.id;const wrong=b.question.options.find(w=>w.id!==id);assert.equal(b.answer(wrong.id).type,'wrong');assert.equal(b.heroHp,85);assert.equal(b.phase,'correction');assert.equal(b.answer(wrong.id).type,'try-again');assert.equal(b.heroHp,85);b.answer(id);assert.equal(b.phase,'resolved');assert.equal(b.energy,1);assert.equal(b.enemyHp,85);assert.ok(b.queue.some(w=>w.id===id));const hp=b.enemyHp;b.answer(id);assert.equal(b.enemyHp,hp);});
test('repeated mistakes rescue child and still reach completion',()=>{const b=battle();const s=finish(b,{wrong:true});assert.ok(s.rescues>=1);assert.equal(s.stars,1);assert.ok(b.heroHp>0);assert.ok(s.review.length);});
test('energy cannot be spent before earned; healing clamps',()=>{const b=battle();assert.equal(b.useSkill('fire').type,'unavailable');b.energy=3;assert.equal(b.useSkill('heal').type,'full-health');assert.equal(b.energy,3);b.heroHp=90;assert.equal(b.useSkill('heal').type,'heal');assert.equal(b.heroHp,100);assert.equal(b.energy,0);});
test('fire shortens combat; queued missed words still reappear',()=>{const normal=battle();finish(normal);const fast=battle();finish(fast,{fire:true});assert.ok(fast.turn<normal.turn);const b=battle();const missed=b.word.id;b.answer(b.question.options.find(w=>w.id!==missed).id);b.answer(missed);if(b.phase==='reward')b.continueReward();else b.advance();finish(b,{fire:true});assert.ok(b.results.filter(r=>r.wordId===missed).length>=2);});
test('hint removes only a distractor and never grants independent mastery',()=>{const p=E.freshProgress(),b=battle(0,{},p);const id=b.word.id;b.energy=6;assert.equal(b.useSkill('hint').type,'hint');assert.equal(b.energy,4);assert.equal(b.question.eliminated.length,1);assert.notEqual(b.question.eliminated[0],id);assert.equal(b.useSkill('hint').type,'unavailable');assert.equal(b.answer(b.question.eliminated[0]).type,'ignored');b.answer(id);if(b.phase==='reward')b.continueReward();else b.advance();finish(b);assert.equal(p.words[id].modes.listen,undefined);});
test('free hints work with zero energy and mark the result assisted',()=>{const b=battle();assert.equal(b.freeHint(),true);assert.equal(b.freeHint(),false);b.answer(b.word.id);assert.equal(b.results[0].independent,false);assert.equal(b.energy,2);});
test('winning persists once; familiarity needs two separate sessions',()=>{const p=E.freshProgress();const b=battle(0,{},p);finish(b);assert.equal(p.sessions,1);assert.equal(b.finish(),null);assert.equal(p.sessions,1);assert.ok(Object.values(p.words).every(w=>!E.mastered(w)));const b2=battle(0,{},p);finish(b2);assert.ok(Object.values(p.words).every(E.mastered));assert.equal(p.chapters.eyes.wins,2);});
test('a new question cannot be skipped; invalid answer has no effect',()=>{const b=battle();assert.equal(b.advance(),false);assert.equal(b.answer('bad-id').type,'ignored');assert.equal(b.turn,1);assert.equal(b.heroHp,100);});
test('progress round trip preserves settings and accomplishments',()=>{const p=E.freshProgress();finish(battle(2,{},p));p.settings.mode='read';p.settings.script='simplified';assert.deepEqual(E.sanitizeProgress(JSON.parse(JSON.stringify(p))),p);const corrupted=E.sanitizeProgress({settings:{mode:'nonsense',options:100,rate:-1},sessions:-2});assert.equal(corrupted.settings.mode,'mixed');assert.equal(corrupted.settings.options,2);assert.equal(corrupted.sessions,0);});
test('assisted sessions cannot dilute best star record',()=>{const p=E.freshProgress();finish(battle(0,{},p));finish(battle(0,{},p),{wrong:true});assert.equal(p.chapters.eyes.stars,3);});
test('sound and written choices never reveal answers through mismatched lengths',()=>{for(let i=0;i<7;i++)for(const mode of ['listen','read','pinyin']){const b=battle(i,{mode,options:4});while(!b.done){for(const option of b.question.options)assert.ok(E.sameLength(option,b.word),`${mode}: ${b.word.traditional}/${option.traditional}`);assert.equal(b.question.options.length,4);if(mode!=='pinyin')assert.equal(new Set(b.question.options.map(w=>w.pinyin)).size,4);b.answer(b.word.id);if(b.phase==='reward')b.continueReward();else b.advance();}}});
test('mixed mode rotates three complementary question formats',()=>{const b=battle(0,{mode:'mixed'}),modes=[];while(!b.done){modes.push(b.question.mode);b.answer(b.word.id);if(b.phase==='reward')b.continueReward();else b.advance();}assert.deepEqual(modes.slice(0,6),['listen','pinyin','read','listen','pinyin','read']);});
test('pinyin options include distinct same-length tone contrasts',()=>{const b=battle(0,{mode:'pinyin',options:4});assert.equal(new Set(b.question.options.map(w=>w.pinyin)).size,4);assert.ok(b.question.options.some(w=>w.id.includes('-tone-')));assert.ok(b.question.options.every(w=>E.sameLength(w,b.word)));});
test('legacy listen default becomes mixed once; explicit new preferences persist',()=>{const old=E.sanitizeProgress({settings:{mode:'listen'},sessions:3,chapters:{eyes:{stars:2,wins:1}}});assert.equal(old.settings.mode,'mixed');assert.equal(old.sessions,3);assert.equal(old.chapters.eyes.stars,2);old.settings.mode='listen';assert.equal(E.sanitizeProgress(old).settings.mode,'listen');});
test('defeating a monster pauses for rewards and awards XP exactly once',()=>{const p=E.freshProgress(),b=battle(0,{},p);for(let i=0;i<4;i++){b.answer(b.word.id);if(i<3)b.advance();}assert.equal(b.phase,'reward');assert.equal(b.wave,1);assert.equal(b.enemyHp,0);assert.equal(p.xp,40);assert.equal(b.advance(),false);assert.equal(b.answer(b.word.id).type,'ignored');assert.equal(b.beginReward('advance'),false);assert.equal(p.xp,40);assert.equal(b.continueReward(),true);assert.equal(b.wave,2);assert.equal(b.enemyHp,100);assert.equal(b.continueReward(),false);assert.equal(p.xp,40);});
test('skill kill pauses then resumes the unanswered question',()=>{const b=battle();b.enemyHp=30;b.energy=3;const id=b.word.id,turn=b.turn;b.useSkill('fire');assert.equal(b.phase,'reward');assert.equal(b.progress.xp,40);b.continueReward();assert.equal(b.word.id,id);assert.equal(b.turn,turn);assert.equal(b.phase,'answer');assert.equal(b.wave,2);assert.equal(b.enemyHp,100);});
test('second monster levels the hero up and applies a bounded heal',()=>{const p=E.freshProgress(),b=battle(0,{},p);let safety=0;while(b.phase!=='reward'&&safety++<10){b.answer(b.word.id);if(b.phase!=='reward')b.advance();}b.continueReward();b.heroHp=65;safety=0;while(b.phase!=='reward'&&safety++<10){b.answer(b.word.id);if(b.phase!=='reward')b.advance();}assert.equal(p.xp,100);assert.equal(b.reward.after.level,2);assert.equal(b.reward.healed,25);assert.equal(b.heroHp,90);const restored=E.sanitizeProgress(JSON.parse(JSON.stringify(p)));assert.equal(E.experience(restored).level,2);b.continueReward();assert.ok(b.done);assert.equal(b.finish().xp,100);assert.equal(p.xp,100);});
test('legacy progress starts at level one and invalid XP is discarded',()=>{assert.equal(E.experience(E.sanitizeProgress({sessions:2})).level,1);assert.equal(E.sanitizeProgress({xp:-10}).xp,0);assert.equal(E.sanitizeProgress({xp:'100'}).xp,0);assert.equal(E.experience({xp:240}).level,3);assert.equal(E.experience({xp:240}).current,40);});
