const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {createPlayer}=require('../recorded-speech.js'),{freshProgress,sanitizeProgress}=require('../engine.js'),C=require('../curriculum.js');
test('every shared character and word has one fixed complete audio asset',()=>{for(const w of C.words){const file=path.join(__dirname,'../assets/audio-neural-v1',w.id+'.mp3');assert.ok(fs.statSync(file).size>500,w.traditional);}});
test('new playback cancels previous word and ignores stale failure',async()=>{const clips=[];let errors=0,ended=0;class FakeAudio{constructor(url){this.url=url;clips.push(this);}play(){return new Promise((resolve,reject)=>{this.reject=reject;});}pause(){this.paused=true;}}const p=createPlayer({AudioClass:FakeAudio,onEnded:()=>ended++});p.play('whole-word-one.mp3',1,()=>errors++);p.play('whole-word-two.mp3',.85,()=>errors++);assert.equal(clips[0].paused,true);assert.equal(clips[1].playbackRate,.85);assert.equal(clips[1].preservesPitch,true);clips[0].reject(Error('cancelled'));await Promise.resolve();assert.equal(errors,0);clips[1].onended();assert.equal(ended,1);});
test('a failed clip reports once and a following clip remains playable',async()=>{const clips=[];let errors=0;class FakeAudio{constructor(){clips.push(this);}play(){return Promise.reject(Error('not allowed'));}pause(){}}const p=createPlayer({AudioClass:FakeAudio});p.play('a.mp3',1,()=>errors++);clips[0].onerror();await Promise.resolve();assert.equal(errors,1);p.play('b.mp3',1,()=>errors++);await Promise.resolve();assert.equal(errors,2);});
test('old voice settings migrate to whole-word audio at original speed without losing learning',()=>{const old={settings:{voice:'old-device',rate:.85},sessions:7,chapters:{eyes:{wins:2,stars:3}}};const p=sanitizeProgress(old);assert.equal(p.settings.voice,'neural-xiaoxiao-v1');assert.equal(p.settings.rate,1);assert.equal(p.sessions,7);assert.equal(p.chapters.eyes.wins,2);assert.equal(p.chapters.eyes.stars,3);assert.equal(p.chapters.eyes.rewardClaims,4);const custom=freshProgress();custom.settings.voice='chosen-device';custom.settings.rate=.7;assert.deepEqual(sanitizeProgress(custom),custom);});
test('chapter preload fetches complete clips once and replay uses the buffered player',async()=>{const clips=[],requests=[];class FakeAudio{constructor(){clips.push(this);}load(){}play(){this.plays=(this.plays||0)+1;return Promise.resolve();}pause(){}}const p=createPlayer({AudioClass:FakeAudio,fetchAudio:async(url,options)=>{requests.push({url,options});return{ok:true,blob:async()=>({size:600})};},urlAPI:{createObjectURL:()=>`blob:clip-${requests.length}`}});assert.deepEqual(await p.preload(['one.mp3','two.mp3','one.mp3']),{loaded:2,total:2});await p.preload(['one.mp3','two.mp3']);assert.equal(requests.length,2);assert.equal(requests[0].options.cache,'force-cache');p.play('one.mp3',1);p.play('two.mp3',1);p.play('one.mp3',1);assert.equal(clips.length,2);assert.equal(clips[0].plays,2);assert.match(clips[0].src,/^blob:/);assert.equal(clips[0].currentTime,0);});
test('preload failure is retryable and never blocks direct tap playback',async()=>{let fail=true,plays=0,errors=0;class FakeAudio{load(){}pause(){}play(){plays++;return Promise.resolve();}}const p=createPlayer({AudioClass:FakeAudio,fetchAudio:async()=>{if(fail)throw Error('offline');return{ok:true,blob:async()=>({size:700})};},urlAPI:{createObjectURL:()=> 'blob:ready'}});assert.equal((await p.preload(['one.mp3'])).loaded,0);p.play('one.mp3',1,()=>errors++);assert.equal(plays,1);assert.equal(errors,0);fail=false;assert.equal((await p.preload(['one.mp3'])).loaded,1);});
test('loading and playing notifications reflect media state and ignore an old clip',()=>{const clips=[],events=[];class FakeAudio{constructor(){clips.push(this);}pause(){}play(){return Promise.resolve();}}const p=createPlayer({AudioClass:FakeAudio,onLoading:url=>events.push('load '+url),onPlaying:url=>events.push('play '+url)});p.play('one.mp3',1);const oldHandler=clips[0].onplaying;p.play('two.mp3',1);oldHandler();clips[1].onplaying();assert.deepEqual(events,['load one.mp3','load two.mp3','play two.mp3']);});
